# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\glitchaka\Desktop\C0D1NG\python\crud\ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(557, 463)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnAgregar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAgregar.setGeometry(QtCore.QRect(20, 120, 71, 31))
        self.btnAgregar.setObjectName("btnAgregar")
        self.btnEliminar = QtWidgets.QPushButton(self.centralwidget)
        self.btnEliminar.setGeometry(QtCore.QRect(340, 120, 71, 31))
        self.btnEliminar.setObjectName("btnEliminar")
        self.btnModificar = QtWidgets.QPushButton(self.centralwidget)
        self.btnModificar.setGeometry(QtCore.QRect(170, 120, 71, 31))
        self.btnModificar.setObjectName("btnModificar")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(470, 120, 71, 31))
        self.btnCancelar.setObjectName("btnCancelar")
        self.tblContacto = QtWidgets.QTableWidget(self.centralwidget)
        self.tblContacto.setGeometry(QtCore.QRect(20, 160, 521, 251))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(8)
        self.tblContacto.setFont(font)
        self.tblContacto.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tblContacto.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tblContacto.setGridStyle(QtCore.Qt.SolidLine)
        self.tblContacto.setRowCount(1)
        self.tblContacto.setColumnCount(3)
        self.tblContacto.setObjectName("tblContacto")
        self.tblContacto.horizontalHeader().setCascadingSectionResizes(False)
        self.tblContacto.horizontalHeader().setStretchLastSection(True)
        self.txtNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNombre.setGeometry(QtCore.QRect(20, 80, 171, 20))
        self.txtNombre.setObjectName("txtNombre")
        self.txtCorreo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCorreo.setGeometry(QtCore.QRect(200, 80, 341, 20))
        self.txtCorreo.setObjectName("txtCorreo")
        self.txtId = QtWidgets.QLineEdit(self.centralwidget)
        self.txtId.setGeometry(QtCore.QRect(20, 30, 81, 20))
        self.txtId.setReadOnly(True)
        self.txtId.setObjectName("txtId")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 47, 14))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 60, 47, 14))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 557, 22))
        self.menubar.setObjectName("menubar")
        self.menuAwesome_APPS = QtWidgets.QMenu(self.menubar)
        self.menuAwesome_APPS.setObjectName("menuAwesome_APPS")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAwesome_APPS.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Contactos"))
        self.btnAgregar.setText(_translate("MainWindow", "Agregar"))
        self.btnEliminar.setText(_translate("MainWindow", "Eliminar"))
        self.btnModificar.setText(_translate("MainWindow", "Modificar"))
        self.btnCancelar.setText(_translate("MainWindow", "Cancelar"))
        self.label.setText(_translate("MainWindow", "ID:"))
        self.label_2.setText(_translate("MainWindow", "Nombre:"))
        self.label_3.setText(_translate("MainWindow", "Correo"))
        self.menuAwesome_APPS.setTitle(_translate("MainWindow", "Awesome APPS"))
